from room import Room
from maze import Maze
my_rooms = []
my_rooms.append('A beautifil fireplace stands before you. What a gorgeous living room.')
my_rooms.append('Ewww what is that smell? Are you in the bathroom?')
my_rooms.append('There is a loarge desk with a computer and other various things on it. Probabaly an office.')
my_rooms.append('A soft fluffy bed entices you to take a nap. You are in the bedroom.')
my_rooms.append('An empty hallway stands before you.')
my_rooms.append('Who left this plate of fresh cookies here? You are in the kitchen.')
my_rooms.append('A glistening chandelier hangs above a large wooden diningroom table.')
my_rooms.append('Ahhh the smell of fresh air. You are outside on the patio.')
my_rooms.append('Mystical rose bushes spread out before you in the lovely garden.')
my_rooms.append('An empty hallway stands before you.')
my_rooms.append('You gaze upward at the towering bookcases around you. This is one big library.')
my_rooms.append('The library continues. I hope you are not lost...')
my_rooms.append('The library continues. I hope you are not lost...')
my_rooms.append('The library continues. I hope you are not lost...')
my_rooms.append('The library continues. I hope you are not lost...')

my_rooms[0].setEast(my_rooms[1])
my_rooms[0].setWest(my_rooms[2])
my_rooms[2].setEast(my_rooms[0])
my_rooms[2].setNorth(my_rooms[3])
my_rooms[3].setSouth(my_rooms[2])
my_rooms[1].setWest(my_rooms[0])
my_rooms[1].setNorth(my_rooms[4])
my_rooms[4].setSouth(my_rooms[1])
my_rooms[4].setNorth(my_rooms[5])
my_rooms[5].setSouth(my_rooms[4])
my_rooms[5].setNorth(my_rooms[6])
my_rooms[6].setSouth(my_rooms[5])
my_rooms[6].setEast(my_rooms[7])
my_rooms[6].setWest(my_rooms[9])
my_rooms[7].setEast(my_rooms[8])
my_rooms[7].setWest(my_rooms[6])
my_rooms[8].setWest(my_rooms[7])
my_rooms[9].setEast(my_rooms[6])
my_rooms[9].setWest(my_rooms[10])
my_rooms[10].setEast(my_rooms[9])
my_rooms[10].setWest(my_rooms[11])
my_rooms[10].setNorth(my_rooms[12])
my_rooms[11].setEast(my_rooms[10])
my_rooms[11].setNorth(my_rooms[13])
my_rooms[12].setSouth(my_rooms[10])
my_rooms[12].setWest(my_rooms[13])
my_rooms[13].setEast(my_rooms[12])
my_rooms[13].setSouth(my_rooms[11])



